name: twntyandsevn
favicon: null
layout_spectrum: 0.3411172707565129
typography_spectrum: 0.3229511638637632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6481641032733023
  lightness: 0.4648869135417044
  saturation: 0.8613692023791373
  rhythmicContrast: 0.4242211524397135
purpose: []
